# Generated by Django 6.0.3 on 2026-07-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='syllabus/'),
        ),
    ]
